### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant

### ISSUE THREAD

**Issue by JulesWebb** [Spcktr/divi-button-event-tagger#1]
Hi Tim

This is a great idea. I installed it to check it out and ended up with the error below.  If you're still supporting this bit, I'd love to use it. 

Fatal error: Uncaught Error: Undefined constant "LINK_HELPER_SELECTOR" in /www/wp-content/plugins/divi-button-event-tagger-main/divi-button-event-tagger.php:46

![2023-10-01_fatal-error_divi-button-event-tagger](https://github.com/Spcktr/divi-button-event-tagger/assets/3140850/59851391-8325-4653-9f64-a22f9fef3535)

Cheers!
Jules

**Comment by Spcktr** [comment]
Hi @JulesWebb 

All Fixed for you! New release added here: https://github.com/Spcktr/divi-button-event-tagger/releases/tag/v1.1.0

**Comment by JulesWebb** [comment]
Wow @Spcktr! That was so fast! 

I installed it, and it's working great. Thank you!
