### ISSUE TITLE
rel="nofollow" added to links

### ISSUE THREAD

**Issue by JulesWebb** [Spcktr/divi-button-event-tagger#3]
@Spcktr rel="nofollow" is being added to the links. 

You can see it live on buttons at https://dogbreedingwebsites.design/

screenshot: [https://app.screencast.com/yAoVsAnq6Lgn0]

Is this something you can remove?

**Comment by Spcktr** [comment]
Hey @JulesWebb 

It looks like the nofollow is being added by divi itself.

I've made a small snippet for you that could potentially resolve this for you. Its specifically only targeting links that have the divi button attribute. 

That said, you might be able to reach out to the divi Devs or the docs there to see if there is just a toggle or an option that might turn that auto insert off.

You can use something like WPCode to insert this on each page, just make sure its in the footer.


```javascript
function removeRelAndNofollow() {
  // Get all anchor links with the class et_pb_button
  const anchors = document.querySelectorAll('a.et_pb_button');

  // Loop through each anchor element
  anchors.forEach(anchor => {
    // Check if the anchor has a 'rel' attribute
    if (anchor.hasAttribute('rel')) {
      // Get the current 'rel' attribute value
      const relAttribute = anchor.getAttribute('rel');
      
      // Check if the 'nofollow' value exists in the 'rel' attribute
      if (relAttribute.includes('nofollow')) {
        // Remove the entire 'rel' attribute
        anchor.removeAttribute('rel');
      }
    }
  });
}
```

Tim

**Comment by JulesWebb** [comment]
@Spcktr 

The Divi Module settings do have the ability to add "nofollow" but that is not ticked off.  See the screenshot link. 
Also, when divi-button-event-tagger is deactivated, the "nofollow" is not included in the link. 

https://app.screencast.com/OHJpWuRsVPSvX

**Comment by Spcktr** [comment]
Hi @JulesWebb 

Strange. I wonder if Divi is doing something in the background to the link when it's changed, this plugin doesn't add anything but the required data-vars for GA. For now, the script above will take care of the rel attrs either way. 

Tim

**Comment by JulesWebb** [comment]
Hi @Spcktr 

Sorry to bug you again, I appreciate your time and help. 

The snippet you provided threw a "Syntax error, unexpected token "const"." on line 3. see screenshot link below. 

https://app.screencast.com/C1ZUsGk888dIq

Thank you!

**Comment by Spcktr** [comment]
Hi @JulesWebb 

Sorry about that, please use the following slimmed down version.

```javascript

// Get all anchor elements on the page
let anchors = document.querySelectorAll('a.et_pb_button');

// Loop through each anchor element
anchors.forEach(anchor => {
  // Check if the 'rel' attribute contains 'nofollow'
  const relAttribute = anchor.getAttribute('rel');
// If it does remove 'rel' attribute
  if (relAttribute && relAttribute.includes('nofollow')) {
    anchor.removeAttribute('rel');
  }
}); 
```
I tested it on the site you link you linked above and it removes the nofollow from the button you pointed at and others as well.  Let me know if you run into issues.

Thanks

**Comment by JulesWebb** [comment]
Hi @Spcktr 

I'm using [Code Snippets Pro](https://codesnippets.pro/) to manage custom code on the site. I'm still getting a Syntax error, an unexpected identifier "anchors" error on line 2. See the screenshot below. 

https://app.screencast.com/WrAO55uSY0mqs

Thank you for sticking with me, I appreciate your time!
Jules

**Comment by Spcktr** [comment]
Hi @JulesWebb 

Ah I see the issue here. Looks like that addon wants to add a PHP function to the sites' functions.php file, rather than to the front end. You can add the above script between some `<script></script>` tags in the theme's footer file.

I'll work on something to auto-remove the `rel='nofollow'` in another release.

Cheers

**Comment by JulesWebb** [comment]
Thank you @Spcktr 

That worked. I'm all set. Thank you so much!

**Comment by Spcktr** [comment]
@JulesWebb 

I've made a new version 1.1.1 that you can install. It will add the same data-vars but wil remove the `rel='nofollow'` from _only_ the button links that this plugin tags. 

Release found here: [v1.1.1](https://github.com/Spcktr/divi-button-event-tagger/releases/tag/v1.1.1)

Once updated, you can remove the script that was added previously. 

Cheers,

**Comment by JulesWebb** [comment]
@Spcktr 

I've deactivated the JS snippet and updated to v1.1.1 and can confirm that rel="nofollow" is not included in the links.

Thank you for all your help!
